### ISSUE TITLE
The removeFromPreviewOnError: true parameter does not work on version higher than 4.5.2

### ISSUE THREAD

**Issue by Gritmatch** [kartik-v/bootstrap-fileinput#1457]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. The following parameter is set in $("#profilepic-dropzone").fileinput

removeFromPreviewOnError: true 

## Expected behavior and actual behavior

I expect the file to be removed completely from the preview. However, it remains in preview as shown in the attachment. 
![2019-08-27_16-52-03](https://user-images.githubusercontent.com/46830254/63807312-6c382780-c8eb-11e9-8c5e-323f8020b989.jpg)

Note that this only happens with fileinput plugin version higher than 4.5.2. When I downgrade to 4.5.2 from 5.0.5, then the issue disappears as in attachment.

![2019-08-27_17-00-08](https://user-images.githubusercontent.com/46830254/63807788-71e23d00-c8ec-11e9-94c3-3367f4905867.jpg)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: jQuery v1.12.4 used by WordPress
- bootstrap-fileinput version: 5.0.5

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
The demo pages do not seem to use removeFromPreviewOnError: true 
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is because - there is a new property `retryErrorUploads` which has been introduced in later releases to allow users to retry upload of errored thumbnails depending on the need.

Refer [ `retryErrorUploads` ](https://plugins.krajee.com/file-input/plugin-options#retryErrorUploads) documentation. This defaults to `true`.

So if you still wish to go ahead and remove errored out thumbnails - then set `retryErrorUploads` to `false` in addition to setting `removeFromPreviewOnError` to `true`

**Comment by Gritmatch** [comment]
Hi Kartik.
Thank you for your help. I tried adding retryErrorUploads:false - did not work. I guess this is because this setting is probably applicable to server-side errors and size error I'm testing for is client side.

Here is JS Fiddle. Try adding a large file >12MB. I would expect the image frame to disappear, but it does not. Image is removed, but the frame stays.

https://jsfiddle.net/gritmatch/te9qpd6w/18/

**Comment by kartik-v** [comment]
Resolved with the above commit.

**Comment by Gritmatch** [comment]
Hi Kartik. Thank you so much for looking into this. The issue is still around though. When I look at your demo https://plugins.krajee.com/file-input-ajax-demo/6, you check for min and max file size. This check works.

Here is an expected behavior, when more than maxFileCount is being added to the dropzone. Only error is shown, extra file frames are not in the dropzone. Good.

![100](https://user-images.githubusercontent.com/46830254/64071223-6e7be800-cc43-11e9-9f8f-0fbf876e9958.jpg)

Where it breaks is when I check for the file size. The frame with the large file is not removed in v5.0.5.

![101](https://user-images.githubusercontent.com/46830254/64071230-9408f180-cc43-11e9-9fb4-4942d7b40560.jpg)

**Comment by kartik-v** [comment]
@Gritmatch  - the issue has been resolved for all such validation checks... it seems you are not using the latest code.

The JS Fiddle you shared uses the old version of the extension - use the latest code from `dev-master` of this repo and retry --- 

As an example of file size validation cross check the [Krajee FAS explorer demo](https://plugins.krajee.com/file-krajee-explorer-fas-demo)

**Comment by Gritmatch** [comment]
Hi kartik. My bad. I updated the reference now to dev-master code and error messages work fine. JS fiddle references updated: https://jsfiddle.net/gritmatch/te9qpd6w/19/

Thank you for this!
