### ISSUE TITLE
Correctly validate persistent file validation errors and display them

### ISSUE THREAD

**Issue by griffgj** [kartik-v/bootstrap-fileinput#1569]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Attempted to isolate options and below is the bare bones code that still produces the error:

<pre><code>var $file_upload = $("#input-705"); 
$file_upload.fileinput({
	theme: 'fas',
	uploadUrl: 'ajax.php',
	allowedFileExtensions: ['txt']
}).on('filebatchselected', function(event, files) {
        $file_upload.fileinput("upload"); 
});</code></pre>

2. Set up test to look like demo here: https://plugins.krajee.com/file-input-ajax-demo/6

## Expected behavior and actual behavior

When running the code above, I expect to get an error telling me the file extension of the file I have dragged into the box/selected is invalid. This does not happen but get a blank red bar instead.

If I remove "allowedFileExtensions", it works. Or if I remove "uploadUrl" it works. Or if I remove the "filebatchselected" event, it works. But if all 3 are present, it doesn't work. The file "ajax.php" does not have any affect (in one testing scenario it existed and in another it didn't and the issue persisted).

The only thing that causes the above code to work properly, that I have found, is adding "minFileCount:1" (when "maxTotalFileCount:1" exists) to the code, which seems to trigger a second error and then all of them are displayed.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.4.1 and 3.5.1
- bootstrap-fileinput version: 5.0.9

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Fixed via above commit. Recheck and let know.

**Comment by kartik-v** [comment]
Fixed via above latest commit. Recheck and let know.

**Comment by griffgj** [comment]
Thank you for such a quick response! Please forgive me for being very inexperienced in this, but I believe I downloaded the updated code and am still experiencing the same issue. Please see my test: http://spider.eng.auburn.edu/makerspace/test.php
