### ISSUE TITLE
Download Action is Invoked when Uploading a CSV File

### ISSUE THREAD

**Issue by amy-mavis-qin** [kartik-v/bootstrap-fileinput#1702]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Click browse and select CSV file

## Expected behavior and actual behavior

When I try to upload CSV file, the download action is invoked and downloads a copy of the CSV file.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- bootstrap-fileinput version: 5.1.5

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Please share your plugin configuration and if you can share a JS Fiddle or similar demo to understand the issue?

**Comment by amy-mavis-qin** [comment]
Demo: https://imgur.com/a/Gd9k7ry 
Preview:
```javascript
function generateAddEditFileOpts(key, caption, typeIfExists, previewUrl, deleteUrl, newPreviewSettings) {
    var opts = {
        theme: "fas",
        allowedFileExtensions: ['jpeg', 'jpg', 'png', 'gif','pdf', 'csv', 'txt'],
        showUpload: false,
        showClose: false,
        dropZoneEnabled: false,
        overwriteInitial: true,
        removeLabel: 'Cancel',
        browseClass: 'btn btn-primary btn-sm',
        removeClass: 'btn btn-secondary btn-sm',
        fileActionSettings: {
            showDrag: false
        },
        removeFromPreviewOnError: true,
        layoutTemplates: {
            main1: '{preview} {remove} {browse}'
        },
        removeTitle: 'Cancel changes',
        showCaption: false
    };

    if(typeof newPreviewSettings !== 'undefined') {
        opts.previewSettings = {
            pdf: {width: calcPdfWidth('#'+key+'Type'), height: "400px"},
            image: {width: "auto", height: "auto", 'max-width': "100%", 'max-height': "100%"}
        }
    }

    if(!typeIfExists) {
        return opts;
    }

    opts.initialPreviewAsData = true;
    opts.initialPreview = [previewUrl];
    opts.initialPreviewConfig = [
        {caption: caption, type: typeIfExists, url: deleteUrl, key: key}
    ];
    opts.defaultPreviewContent = initialFileMsg;
    opts.initialPreviewDownloadUrl = [previewUrl];

    var hideControlsVar = key.replace(/^.*\./,'') + 'HideControls';
    if(typeof GlobalVars !== 'undefined' && typeof GlobalVars[hideControlsVar] !== 'undefined') {
        console.log("hideControls for " + key);
        opts.showRemove = false;
        opts.showBrowse = false;
        opts.layoutTemplates.actionDelete = "";
    }

    return opts;
}
```

**Comment by kartik-v** [comment]
This actually is an issue with the OS file system configuration... where local applications (like MS Excel/Libre Calc etc.) will try to download the CSV files when previewed via Browser. 

Currently the way this was fixed in the plugin is to prevent PREVIEW of CSV files by default (and remove it from allowedPreviewFileTypes and allowedPreviewFileExtensions) and this avoided that issue. You may need to check it accordingly. Else, you can overcome it by changing the default local filesystem CSV viewer to something else.

**Comment by MitchellBarker** [comment]
I also just spent a lot of time looking for this issue. Couldn't find any mention of it in the docs, and I finally just stumbled onto this issue (thanks @amy-mavis-qin ).

I was also working with csv files and the only way I could fix the issue describe was by doing this:
`disabledPreviewTypes: ['text'],`

You led me down the right path @kartik-v, but definitely seems like something that should be looked into for a future issue :)

**Comment by MMV96** [comment]
There is any update about this issue?
I still have the same problem

Thank you

**Comment by kartik-v** [comment]
As mentioned this is currently not an issue which can be solved in the plugin - but more to do with your local client OS and browser settings. CSV files unfortunately are downloaded by the browser on Windows/other platforms instead of allowing them to be previewed. If you have any other suggestion do let know... currently the options when working with CSV files are


Options;

1. You can disable preview for CSV files in the plugin as mentioned in my previous comment - so your app previews only other files but not CSV files. You can use another JS library to read CSV files and transform them to a previewable one.
2. If you do want to preview CSV files... then you should let your application users upload without the CSV extension - e.g. change the filenames to some other extension (e.g. **.tab** or **.txt** or compressed as **.zip**) so that they will be previewed and not downloaded.
