### ISSUE TITLE
Enhancements and revamp of all error events

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/bootstrap-fileinput#203]
The following error events will be revamped to allow better control of parameters. This change would have a minor impact on BC. Instead of separate parameters as earlier - in each of the events, the parameters will be returned as a single object, for example:

### fileerror
This event is triggered when a client validation error is encountered for an uploaded file. This allows access to an object `params` as a parameter.

- `data`: object/associative array containing the following 
    - `id`: the preview thumbnail identifier (or undefined if not available)
    - `index`: the file index/preview thumbnail index (or undefined if not available)
    - `file`: the file object (or undefined if not available)
    - `reader`: the file reader instance (or undefined if not available)
    - `files`: the file stack array (or empty object if not available).

**Example:**
```js
$('#input-id').on('fileerror', function(event, params) {
   console.log(params.id);
   console.log(params.index);
   console.log(params.file);
   console.log(params.reader);
   console.log(params.files);
});
```

### fileuploaderror
This event is triggered when an upload or file input validation error is encountered primarily for ajax uploads (through the upload icon for each thumbnail or for every file uploaded when uploadAsync is `true`). Additional parameters available are: 
- `data`: This is a data object (associative array) that sends the following information, whose keys are:
    - `form`: the FormData object which is passed via XHR2 (or empty object if not available).
    - `files`: the file stack array (or empty object if not available).
    - `extra`: the `uploadExtraData` settings for the plugin (or empty object if not available).
    - `response`: the data sent via ajax response (or empty object if not available).
    - `reader`: the FileReader instance if available
    - `jqXHR`: the `jQuery XMLHttpRequest` object used for this transaction (if available).
    - `id`: the identifier of each file's parent thumbnail div element in the preview window.
    - `index`: the zero-based index of the file in the file stack.

```js
$('#input-id').on('fileuploaderror', function(event, data, previewId, index) {
    var form = data.form, files = data.files, extra = data.extra, 
        response = data.response, reader = data.reader;
    console.log('File upload error');
});
```

### filebatchuploaderror
This event is triggered when any error is faced in the synchronous batch upload (i.e. when `uploadAsync` is `false`). Additional parameters available are: 

- `data`: This is a data object (associative array) that sends the following information, whose keys are:
    - `form`: the FormData object which is passed via XHR2 (or empty object if not available).
    - `files`: the file stack array (or empty object if not available).
    - `extra`: the `uploadExtraData` settings for the plugin (or empty object if not available).
    - `response`: the data sent via ajax response (or empty object if not available).
    - `reader`: the FileReader instance if available
    - `jqXHR`: the `jQuery XMLHttpRequest` object used for this transaction (if available).

```js
$('#input-id').on('filebatchuploaderror', function(event, data) {
    var form = data.form, files = data.files, extra = data.extra, 
        response = data.response, reader = data.reader;
    console.log('File upload error');
});
```

### filedeleteerror
This event is triggered when an error is faced in deletion of each thumbnail file in the `initialPreview` content set. Additional parameters available are: 

- `data`: This is a data object (associative array) that sends the following information, whose keys are:
    - `id`: the identifier of the preview thumbnail container.
    - `index`: the zero-based index of the file in the preview container.
    - `response`: the data sent via ajax response (or empty object if not available).
    - `extra`: the output of `deleteExtraData` object.
    - `jqXHR`: the `jQuery XMLHttpRequest` object used for this transaction (if available).

```js
$('#input-id').on('filedeleteerror', function(event, data) {
    console.log('File delete error');
});
```
#### filecustomerror
This event is triggered manually by the user from one of the other events by returning an error object from the source event. Refer Event Manipulation section for details. Additional parameters available are: 

- `data`: This is a data object (associative array) that sends the following information, whose keys are:
    - `form`: the FormData object which is passed via XHR2 (or empty object if not available).
    - `response`: the aborted data sent when returned when triggering the validation error from the source event. 
    - `files`: the file stack array (or empty object if not available).
    - `extra`: the `uploadExtraData` settings for the plugin (or empty object if not available).
    - `reader`: the FileReader instance if available
    - `jqXHR`: the `jQuery XMLHttpRequest` object used for this transaction (an empty object usually).

```js
$("#input").on('filecustomerror', function(event, params) {
   console.log(params.id);
   console.log(params.index);
   console.log(params.data);
});
```

**Comment by kartik-v** [comment]
Resolved via upgrade to release v4.1.8.

**Comment by Kaldrax** [comment]
When setting maxFileSize the fileerror event is not triggered if you try to select a file larger than the set size. Instead of msgSizeTooLarge the general error message is shown.

The file still gets uploaded if .fileinput('upload') is called. (I'm using an external button)

**Comment by kartik-v** [comment]
If you are using ajax upload then you need to trap the `fileuploaderror` event.

The `fileerror` is only for non-ajax form based uploads.

**Comment by Kaldrax** [comment]
Thanks I didn't know that. Still the fileuploaderror (in my case filebatchuploaderror) is only triggered AFTER the upload attempt. I thought fileerror would be the right event to trigger BEFORE any upload happens, like right when the error message is displayed.

Additionally what's very confusing: shouldn't there be a specific error message for file size exceeded?
Because it only shows me "File Upload Error" and not the msgSizeTooLarge.
