### ISSUE TITLE
Wrong order in initialPreviewConfig

### ISSUE THREAD

**Issue by koxu1996** [kartik-v/bootstrap-fileinput#839]
Finally I figured out the problem with sorting. I setted `uploadAsync: true`. When you upload images for eg. _1.png_, _2.png_, _3.png_, then upload is running in alphabetical order, but `initialPreviewConfig` not always will be `["1.png", "2.png", "2.png"]`, because it depends on responses end time:
![](https://i.snag.gy/24bCYV.jpg)
In this case I got `["1.png", "3.png", "2.png"]`, but in preview I saw images in alphabetical order. So after switching first image (_1.png_ in preview) with second (_2.png_ in preview), the `initialPreviewConfig` is `["3.png", "1.png", "2.png"]`, but should be `["2.png", "3.png", "1.png"]`.

Tomorrow I will provide video which simply show this issue.

**Comment by kartik-v** [comment]
Yes you must not overwrite the `initialPreviewConfig` blindly after upload for your case and when using async uploads (`uploadAsync` is true).

For that scenario above you must return `initialPreview` and `initialPreviewConfig` directly as a JSON response in the upload server action as mentioned in [ajax demo example # 6](http://plugins.krajee.com/file-input-ajax-demo/6) which will return a preview specific only to the file uploaded.

**Comment by koxu1996** [comment]
@kartik-v Of course I am returning `initialPreview` and `initialPreviewConfig`. Lets add `filesorted` event to see what images are switched:
```
function(event, params) {
    alert('Switched ' + params.stack[params.newIndex].key + 
    ' from index ' + params.oldIndex + ' to index ' + params.newIndex);
}
```
When sometimes initalPreviewConfig is in nonalphabetical order and we move for eg. `2.png`, then we see in alert that we switched `3.png`! You can watch this bug on [video](https://youtu.be/ddLKiUzssSY).

**Comment by kartik-v** [comment]
@koxu1996 I see. The issue is not with initialPreview showing incorrectly. But it is more to do with file sorting using drag and drop... for `uploadAsync` set to `true` and you have a special case where you are directly returning initial preview after the upload.

Since it uses the sortable plugin to drag sort... the plugin will only return the begin target and end target. and the files that are not uploaded yet will not be understood by the third party sortable plugin.

It is thus recommended to not use `uploadAsync` specifically for the use case if you want to sort - because the file stack will not have the right data to display.

The recommended options if you want to drag and sort the thumbnails in the preview are:

- *OPTION 1:* Use with `uploadAsync` set to `false`. In that case the entire `initialPreview` will be directly rendered and understood by the sortable plugin.
- *OPTION 2:* Use with `uploadAsync` set to `true` BUT do not return the `initialPreview` immediately after upload. This will then show the thumbnails uploaded but will not allow drag and drop sorting. You can show `initialPreview` rather on page refresh where the sorting will work correctly

**Comment by kartik-v** [comment]
There is a bit of enhancement I think I can include to prevent sorting when `uploadAsync` is `true` until all files are uploaded. Will update.

**Comment by koxu1996** [comment]
What about fixing order in `initialPreview`? It will allow to sort correctly with `async: true`

**Comment by koxu1996** [comment]
You don't understand me. 
I am talking about situation when all images are uploaded.

**Comment by kartik-v** [comment]
Checking and will update.

**Comment by kartik-v** [comment]
Checking and will update... can you paste the code snippet that reflects the plugin configuration for your use case.

**Comment by koxu1996** [comment]
```
$("#w0").fileinput({
    'uploadUrl': '/image/upload',
    'async': true,
});
$('#w0').on('filesorted', function(event) {
    function(event, params) {
        //parms.stack[params.newIndex] is image which we moved
        alert('Moved ' + params.stack[params.newIndex].key + ' from index ' + params.oldIndex + ' to index ' + params.newIndex);
        }
});
```
You can see on video (0:24) that when I moved `2.png`, I got alert `Switched 3.png ...`

**Comment by kartik-v** [comment]
Fixed and enhanced better. 

It also includes a better way to prevent sortable to be activated when the uploads are in process. A complex use case is for you to set an `initialPreview` on page load... and then also try these async uploads that return `initialPreview` from server response (when `uploadAsync` is true)..

**Comment by koxu1996** [comment]
Almost perfect, but one problem remains. You removed enhancement for #828 which allowed to sort images uploaded by clicking upload icons. Can you restore it and make working along with https://github.com/kartik-v/bootstrap-fileinput/commit/0aab773b9c8f2a331d61b490438ea3c539e8bd71?

**Comment by kartik-v** [comment]
Yes as mentioned ... it had to be removed [as per my comment earlier](https://github.com/kartik-v/bootstrap-fileinput/issues/839#issuecomment-272628797)... to ensure consistent sortable behavior.

Else you will have issues if you have 10 files being uploaded and say the 4th, 5th, and 8th files are not yet uploaded ... and the sorting order will change the initialPreviewConfig in an undesired manner.

Hence the fix ensures, the sorting can be done only after all files are uploaded.

**Comment by kartik-v** [comment]
The sort after single file upload still exists. But yes as mentioned  [as per my comment earlier](https://github.com/kartik-v/bootstrap-fileinput/issues/839#issuecomment-272628797)... if you click batch upload with `uploadAsync` as `true`, the sorting cannot be done now until all files are uploaded. This to ensure consistent sortable behavior and expected initialPreview.

Else you will have issues if you have 10 files being uploaded and say the 4th, 5th, and 8th files are not yet uploaded ... and if someone sorts it before the sorting order will change the initialPreviewConfig in an undesired manner.

Hence the fix ensures, the sorting can be done only after all files are uploaded.

**Comment by Minotti** [comment]
@koxu1996 this problem has been solved?

I am experiencing the same problem.

**Comment by koxu1996** [comment]
@Minotti There were a few bugs, but the problem was solved few years ago - not sure if it still works.

**Comment by Minotti** [comment]
@koxu1996 I suspect it has been resolved in the past and is now not working again.
